"""Regenerate README.md from an already-executed README.ipynb.

    python scripts/make_readme.py           # convert the notebook to README.md
    python scripts/make_readme.py --gifs    # also rebuild the animated GIFs (slow, and see below)

This script does NOT run the notebook. Run README.ipynb yourself, in Jupyter, and once its output looks the
way you want, run this to turn it into README.md. (The simulator is not reproducible even with a fixed seed
-- see issue #14 -- so re-executing the notebook here would silently replace output you had just checked.)

README.md is the *verbatim* nbconvert output of README.ipynb, with relative links rewritten to absolute
GitHub URLs. Never edit README.md by hand: edit README.ipynb, run it, and regenerate.

Why the link rewriting is necessary: pyproject.toml sets ``readme = "README.md"``, so this file becomes the
PyPI long description, and PyPI cannot resolve repo-relative paths. Note that images must be served from
raw.githubusercontent.com -- a github.com/.../blob/... URL returns an HTML page, not the image, so it will
not render.

The GIFs (--gifs) stand in for the notebook's two ipywidgets slider cells, which cannot survive nbconvert
(and which GitHub cannot render inside a notebook either). They are rendered offscreen with matplotlib, not
screen-recorded. They are off by default because building them re-runs the simulations, which are not
reproducible (#14), so every rebuild rewrites a couple of hundred KB of binary even when nothing changed --
you only want that when you have actually changed the slider cells. Without --gifs, this script leaves them
untouched and is byte-for-byte idempotent.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FILES = ROOT / "README_files"
REPO = "UC-Davis-molecular-computing/batss"
BRANCH = "main"

RAW = f"https://raw.githubusercontent.com/{REPO}/{BRANCH}"  # serves file *content* (images)
BLOB = f"https://github.com/{REPO}/blob/{BRANCH}"  # serves a rendered *page* (notebooks, source)

BANNER = """<!--
  DO NOT EDIT THIS FILE. It is generated from README.ipynb by scripts/make_readme.py, and any hand edits
  will be silently overwritten the next time it is regenerated.

  To change the README, edit README.ipynb, run it in Jupyter, then run:  python scripts/make_readme.py
  See CONTRIBUTING.md.
-->

"""

# Applied in order to the markdown nbconvert emits.
REWRITES: list[tuple[re.Pattern[str], str]] = [
    # Images and other raw assets: README_files/foo.png -> raw.githubusercontent.com/...
    (re.compile(r"\]\(README_files/"), f"]({RAW}/README_files/"),
    # Files that should render as a page rather than download as raw text.
    (re.compile(r"\]\((examples/[^)\s]+|benchmark/[^)\s]+|CONTRIBUTING\.md|LICENSE)\)"), rf"]({BLOB}/\1)"),
]

FPS = 20


# --------------------------------------------------------------------------------------------------
# The animated GIFs (--gifs only)
# --------------------------------------------------------------------------------------------------


def make_gifs() -> None:
    """Rebuild the GIFs that stand in for README.ipynb's two slider cells. Takes about 12 seconds.

    These re-run their own simulations rather than reusing the notebook's, so the trajectory they show is
    a different sample from the one plotted above them in the README. That is fine -- they illustrate what
    dragging the slider does, not a specific run -- but it does mean the bytes change on every rebuild.
    """
    print("rebuilding the slider GIFs ...")

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.animation import FuncAnimation, PillowWriter

    from batss import Simulation, species
    from batss.snapshot import StatePlotter

    r, f = species("R F")
    rxns = [r >> 2 * r, r + f >> 2 * f, f >> None]

    # The `widgets.interact(plot_row, ...)` cell: a barplot of one configuration, scrubbed over time.
    n = 10**7
    sim = Simulation({r: n // 2, f: n - n // 2}, rxns, seed=0)
    sim.run(10.0, 0.01)
    history = sim.history

    fig, ax = plt.subplots(figsize=(4, 3))
    bars = ax.bar(list(history.columns), [0] * len(history.columns), color=["#1f77b4", "#ff7f0e"])
    ax.set_ylim(0, sim.n)
    ax.set_xlabel("species")
    ax.set_ylabel("count")

    def draw(row: int):
        for bar, value in zip(bars, history.iloc[row]):
            bar.set_height(value)
        ax.set_title(f"Lotka-Volterra at time {history.index[row]:.2f}")
        return bars

    # PillowWriter grabs raw canvas frames, so unlike savefig it never applies bbox_inches="tight".
    # With matplotlib's default margins there is not enough room below the axes for the tick labels *and*
    # the x-label, so the x-label falls off the bottom of the GIF. Lay the figure out explicitly -- after
    # drawing a frame, so that the title is present and tight_layout reserves room for it too.
    draw(0)
    fig.tight_layout()

    FuncAnimation(fig, draw, frames=range(0, len(history), 10), blit=False).save(
        FILES / "lv_bar_slider.gif", writer=PillowWriter(fps=FPS), dpi=80
    )
    plt.close(fig)

    # The `sim.snapshot_slider('time')` cell: batss driving its own StatePlotter through the history.
    n = 10**5
    live = Simulation({r: n // 2, f: n - n // 2}, rxns, seed=1)
    plotter = StatePlotter()
    live.add_snapshot(plotter)
    live.run(20.0, 0.1)

    def scrub(index: int) -> list:
        # set_snapshot_index is exactly what the slider calls, so this animates the real widget behaviour.
        live.set_snapshot_index(index)
        return []

    assert plotter.fig is not None
    scrub(0)
    plotter.fig.tight_layout()  # same PillowWriter clipping hazard as above

    FuncAnimation(plotter.fig, scrub, frames=range(0, len(live.configs), 2), blit=False).save(
        FILES / "lv_snapshot_slider.gif", writer=PillowWriter(fps=FPS), dpi=80
    )
    plt.close(plotter.fig)

    for gif in sorted(FILES.glob("*.gif")):
        print(f"  wrote {gif.relative_to(ROOT)}  ({gif.stat().st_size / 1024:.0f} KB)")


# --------------------------------------------------------------------------------------------------
# Checks
# --------------------------------------------------------------------------------------------------


def check_notebook_executed() -> None:
    """A notebook with no stored outputs would silently convert to a README with no plots or tables."""
    notebook = json.loads((ROOT / "README.ipynb").read_text(encoding="utf-8"))
    code_cells = [cell for cell in notebook["cells"] if cell["cell_type"] == "code"]
    if not any(cell.get("outputs") for cell in code_cells):
        raise SystemExit(
            "ERROR: README.ipynb has no stored outputs. Run it in Jupyter first, then re-run this script."
        )


def warn_if_gifs_stale() -> None:
    """The GIFs are not rebuilt by default, so they can quietly fall behind the notebook."""
    gifs = sorted(FILES.glob("*.gif"))
    stale = [gif for gif in gifs if gif.stat().st_mtime < (ROOT / "README.ipynb").stat().st_mtime]
    if stale:
        print(
            f"  note: README.ipynb is newer than {len(stale)} of {len(gifs)} GIF(s). "
            f"If you changed the slider cells, re-run with --gifs."
        )


# --------------------------------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--gifs",
        action="store_true",
        help="also rebuild the slider GIFs (~12s; re-runs the simulations, so the bytes change every time)",
    )
    args = parser.parse_args()

    check_notebook_executed()

    if args.gifs:
        make_gifs()

    # nbconvert only overwrites the images for cells that still exist, so stale ones from a previous
    # layout would otherwise linger forever, indistinguishable from live ones.
    for stale in FILES.glob("README_*.png"):
        stale.unlink()

    print("converting README.ipynb -> README.md ...")
    subprocess.run(
        [sys.executable, "-m", "jupyter", "nbconvert", "--to", "markdown", "README.ipynb"],
        cwd=ROOT, check=True,
    )

    readme = ROOT / "README.md"
    md = readme.read_text(encoding="utf-8")

    # tqdm redraws a progress bar by overwriting the line with \r; keep only the final frame.
    md = re.sub(r"[^\n]*\r(?!\n)", "", md)

    # Drop outputs that only make sense in a live notebook. A tqdm progress bar and an ipywidgets slider
    # are useful when running the notebook, but nbconvert renders them as a stale text repr -- a progress
    # bar frozen at "0%|", or "interactive(children=(IntSlider(...". Both are pure noise in the README.
    for junk in (
        r"^[ \t]*\d+%\|[^\n]*\n",  # tqdm:  0%|          | 0/10.0 [00:00<?, ? time simulated/s]
        r"^[ \t]*\d+ time simulated \[[^\n]*\n",  # tqdm, before the first update
        r"^[ \t]*interactive\(children=\([^\n]*\n",  # ipywidgets slider repr
    ):
        md = re.sub(junk, "", md, flags=re.MULTILINE)

    # A DataFrame's HTML repr carries a <style scoped> block of CSS. GitHub's sanitizer strips the <style>
    # element but then renders its text content as visible prose, so the raw CSS (".dataframe tbody tr th
    # {...}") appears above every table. Drop the CSS; the <table> itself renders fine without it.
    md = re.sub(r"[ \t]*<style scoped>.*?</style>\n?", "", md, flags=re.DOTALL)

    md = re.sub(r"\n{4,}", "\n\n\n", md)  # collapse the blank runs those leave behind

    for pattern, replacement in REWRITES:
        md = pattern.sub(replacement, md)

    # Fail loudly rather than shipping a README that is broken on PyPI or still refers to the old package.
    if "ppsim" in md:
        raise SystemExit("ERROR: a 'ppsim' reference survived into README.md")
    leftover = re.findall(r"\]\((README_files/|examples/|benchmark/)[^)\s]*\)", md)
    if leftover:
        raise SystemExit(f"ERROR: relative link(s) survived into README.md, which PyPI cannot resolve: {leftover}")
    if "<style" in md or "<script" in md:
        raise SystemExit("ERROR: a <style>/<script> block survived; GitHub renders its contents as visible text")

    # An HTML comment is invisible in the rendered page, but anyone who opens the file sees it immediately.
    md = BANNER + md
    readme.write_text(md, encoding="utf-8", newline="\n")

    images = sorted(path.name for path in FILES.glob("README_*.png"))
    print(f"wrote README.md ({len(md):,} chars) and {len(images)} image(s) in README_files/")
    if not args.gifs:
        warn_if_gifs_stale()


if __name__ == "__main__":
    main()
